#en el directorio donde estan los archivos docker
#docker compose down
#docker compose up

version: "3"
services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/bbdd
      - DATABASE_USERNAME=ROOT
      - DATABASE_PASSWORD=123245
    depends_on:
      - mysqldb

  mysqldb:
    container_name: "mysqldb"
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - #Bind volumens - el volumen se adiere al sistema de archivos de la app
      - #./mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "BBDD"
      MYSQL_USER: "ROOT"
      MYSQL_PASSWORD:"12345"
      MYSQL_ROOT_PASSWORD: "12345"

volumes:
  mysql-data:
    external: false

# por defecto los volumenes no son externos.

